<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $now   = Time::now()->toDateTimeString();
        $month = Time::now()->subMonths(2)->toDateTimeString();

        $data = [
            [
                'vision_id'              => 1,
                'office_id'              => 3,
                'budget_cycle_stage_id'  => 6,
                'created_by'             => 3,
                'project_code'           => 'CEO-2025-DR-001',
                'title'                  => 'Talubangi Flood Control Phase II',
                'description'            => 'Reinforced concrete revetment along Binicuil Creek segment in Brgy. Talubangi.',
                'status'                 => 'published',
                'fiscal_year'            => 2025,
                'barangay'               => 'Talubangi',
                'allocated_amount'       => '12500000.00',
                'obligated_amount'       => '9800000.00',
                'disbursed_amount'       => '6200000.00',
                'target_completion_date' => '2026-03-31',
                'published_at'           => $month,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'vision_id'              => 2,
                'office_id'              => 6,
                'budget_cycle_stage_id'  => 5,
                'created_by'             => 6,
                'project_code'           => 'CAO-2025-AG-014',
                'title'                  => 'Sugarcane Mechanization Support Package',
                'description'            => 'Subsidized tractor attachments and training for smallholder farmers in upland barangays.',
                'status'                 => 'published',
                'fiscal_year'            => 2025,
                'barangay'               => 'Camansi',
                'allocated_amount'       => '4500000.00',
                'obligated_amount'       => '4500000.00',
                'disbursed_amount'       => '2100000.00',
                'target_completion_date' => '2025-12-15',
                'published_at'           => $month,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'vision_id'              => 3,
                'office_id'              => 4,
                'budget_cycle_stage_id'  => 4,
                'created_by'             => 4,
                'project_code'           => 'CHO-2025-HL-003',
                'title'                  => 'Barangay Health Station Upgrade – Binicuil',
                'description'            => 'Renovation of BHS including birthing facility, cold chain, and waiting area.',
                'status'                 => 'approved',
                'fiscal_year'            => 2025,
                'barangay'               => 'Binicuil',
                'allocated_amount'       => '2800000.00',
                'obligated_amount'       => '0.00',
                'disbursed_amount'       => '0.00',
                'target_completion_date' => '2026-06-30',
                'published_at'           => null,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'vision_id'              => 4,
                'office_id'              => 2,
                'budget_cycle_stage_id'  => 3,
                'created_by'             => 2,
                'project_code'           => 'CPDO-2026-DG-001',
                'title'                  => 'Open Budget Portal & Citizen Feedback Module',
                'description'            => 'Development and hosting of the Kabankalan City budget transparency web portal.',
                'status'                 => 'under_review',
                'fiscal_year'            => 2026,
                'barangay'               => null,
                'allocated_amount'       => '1500000.00',
                'obligated_amount'       => '0.00',
                'disbursed_amount'       => '0.00',
                'target_completion_date' => '2026-09-30',
                'published_at'           => null,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'vision_id'              => 1,
                'office_id'              => 3,
                'budget_cycle_stage_id'  => 2,
                'created_by'             => 3,
                'project_code'           => 'CEO-2026-DR-002',
                'title'                  => 'Camugao Evacuation Center Retrofit',
                'description'            => 'Structural assessment and retrofit of multipurpose hall for disaster use.',
                'status'                 => 'submitted',
                'fiscal_year'            => 2026,
                'barangay'               => 'Camugao',
                'allocated_amount'       => '3200000.00',
                'obligated_amount'       => '0.00',
                'disbursed_amount'       => '0.00',
                'target_completion_date' => '2027-01-31',
                'published_at'           => null,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'vision_id'              => 3,
                'office_id'              => 5,
                'budget_cycle_stage_id'  => 1,
                'created_by'             => 5,
                'project_code'           => 'CSWDO-2026-SP-007',
                'title'                  => 'Senior Citizen Wellness Outreach',
                'description'            => 'Mobile clinic and food packs for indigent seniors in coastal barangays.',
                'status'                 => 'draft',
                'fiscal_year'            => 2026,
                'barangay'               => 'Tagukon',
                'allocated_amount'       => '850000.00',
                'obligated_amount'       => '0.00',
                'disbursed_amount'       => '0.00',
                'target_completion_date' => '2026-11-30',
                'published_at'           => null,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'vision_id'              => 2,
                'office_id'              => 6,
                'budget_cycle_stage_id'  => 6,
                'created_by'             => 6,
                'project_code'           => 'CAO-2024-AG-022',
                'title'                  => 'Municipal Fish Landing Facility Repair',
                'description'            => 'Completed repair of ice plant and landing ramp at coastal landing site.',
                'status'                 => 'completed',
                'fiscal_year'            => 2024,
                'barangay'               => 'Tabugon',
                'allocated_amount'       => '1900000.00',
                'obligated_amount'       => '1900000.00',
                'disbursed_amount'       => '1900000.00',
                'target_completion_date' => '2024-10-31',
                'published_at'           => Time::parse('2024-08-01')->toDateTimeString(),
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'vision_id'              => 1,
                'office_id'              => 3,
                'budget_cycle_stage_id'  => 1,
                'created_by'             => 3,
                'project_code'           => 'CEO-2024-RD-099',
                'title'                  => 'Deferred Road Widening – Linao',
                'description'            => 'Project cancelled after right-of-way negotiations stalled.',
                'status'                 => 'cancelled',
                'fiscal_year'            => 2024,
                'barangay'               => 'Linao',
                'allocated_amount'       => '8000000.00',
                'obligated_amount'       => '0.00',
                'disbursed_amount'       => '0.00',
                'target_completion_date' => null,
                'published_at'           => null,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
        ];

        $this->db->table('projects')->insertBatch($data);
    }
}
